### ISSUE TITLE
Move web page to igraph.org

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph.org#1]
_From @gaborcsardi on November 6, 2013 15:31_

In progress.

TODO list. These are needed for the move:
- [x] Get started with Python 
- [x] Python docs
- [x] R PDF manual
- [x] C PDF manual
- [x] C info docs
- [ ] check for broken links
- [x] Downloads
- [x] Warning banner on old docs pages at sourceforge
- [x] Add version number to downloads section, and maybe docs section as well
- [x] nightly sanitize input
- [x] Update first section(s) of C manual, installation, etc. Make sure it is up to date.
- [x] Check for links to sourceforge everywhere. E.g. in the R package, in the docs, etc. These need to be updated.
- [x] Add google analytics.

These are optional:
- [ ] Make search work.
- [ ] Make sure PPA works, add links to PPA.
- [ ] C HTML bundle
- [ ] Affix does not work on NEWS page
- [ ] Create NEWS file(s) automatically from Jekyll posts
- [x] Icons instead of [R] [C] and [PY]
- [ ] Wiki
- [ ] Wiki gallery
- [ ] Screenshots and examples
- [ ] RSS feed for news
- [ ] Add links to old docs
- [ ] Add version number to navbar (?)
- [ ] nightly sorting 
- [ ] nightly remove old files
- [ ] nicer pygments

_Copied from original issue: igraph/igraph#535_

**Comment by gaborcsardi** [comment]
3a4090ff71084f898c58649794dcaa7f28a699f9 reorganized the the web pages significantly. R/igraph, python-igraph and C igraph are different "products" now.

**Comment by gwidryj** [comment]
Could you please check for broken links? Manual page http://igraph.org/c/doc/ does not work (for python-igraph as well).

**Comment by gaborcsardi** [comment]
@gwidryj Thanks, fixed the links, except for the download ones, I'll fix those, too, ASAP.

**Comment by ntamas** [comment]
It seems that @gaborcsardi is in the process of moving igraph.org to Github Pages. (He made a few commits just a few minutes ago). Hopefully things will be fixed soon. Stay tuned.

**Comment by gaborcsardi** [comment]
Yeah, my credit card expired and the old website was suspended, so this was a good time to move.

This means no dynamic pages, of course, so no nightlies, but we haven't used them, anyway. I'll the released versions as static downloads.

**Comment by ntamas** [comment]
@gaborcsardi can we still keep the original `/nightly/steal/c/` and `/nightly/get/c/` style links working (even if they are static downloads or redirects to the actual downloads)? The Homebrew formula and the `setup.py` script for `python-igraph` depend on these URLs.

**Comment by gaborcsardi** [comment]
@ntamas temporarily, yes. But we should rather link to GH releases instead, so ideally homebrew and pip should be updated....

**Comment by ntamas** [comment]
Sure, but then we need to upload our own tarballs to GH releases first - the current tarball for 0.7.1 seems to be just a snapshot of the repo with all sorts of unnecessary stuff (e.g., presentations) and no `./configure` script.

**Comment by gaborcsardi** [comment]
Sure, I am doing that right now.

**Comment by gaborcsardi** [comment]
OK, I added all referenced files to /nightly and also some releases to igraph/igraph and igraph/python-igraph. 

Let me know if sg is missing. I am not sure what exactly is referenced by the pip installer and brew.
