### ISSUE TITLE
R docs: Argument names wrapped too tightly after restyling

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph.org#15]
After the docs were restyling, argument names for the R docs are wrapped too tightly. Screenshot:

![image](https://user-images.githubusercontent.com/1212871/73062560-02717900-3e9d-11ea-8d6f-e0d5ba3b78ed.png)

**Comment by ntamas** [comment]
Same happened for the C docs but I've already fixed it there. I'm going to fix it for the R docs as well.

**Comment by ntamas** [comment]
Fixed in igraph/igraph.org@c3e95887
