### ISSUE TITLE
Py docs: missing icons and bad header styling

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph.org#16]
The screenshot is from the Python tutorial. Notice missing icon and bad header formatting (rounded corner, gap above).

![image](https://user-images.githubusercontent.com/1212871/73063202-8d9f3e80-3e9e-11ea-8c31-7947cbe81ec2.png)

**Comment by ntamas** [comment]
Yes, this still needs some work; the problem is that the Sphinx template I was using for generating the HTML for the manual is stuck on Bootstrap 3.x while the rest of the homepage was updated for Bootstrap 4.x. I need to find a Sphinx Bootstrap template that supports Bootstrap 4.x
