### ISSUE TITLE
C/igraph docs: Many of the links don't work due to upper/lowercase issue

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph.org#27]
Currently, many of the links in the C/igraph docs on the website do not work, apparently due to a case sensitivity issue. Take a look here and try some links:

https://igraph.org/c/doc/igraph-introduction.html

E.g., this link does not work:

https://igraph.org/c/doc/igraph-Introduction.html#idm209455317712

because of the capital `I` in `Introduction`. Changing that to lowercase fixes it. This works:

https://igraph.org/c/doc/igraph-introduction.html#idm209455317712

**Comment by ntamas** [comment]
This could be an issue with the documentation generation on macOS. On macOS, the filesystem is case-aware, but not case-sensitive. On my machine, the files appear in uppercase when I generate the docs. However, it can be the case that somehow they become lowercase during publication. I'll investigate this.

**Comment by ntamas** [comment]
Even in the repo, the [filenames are in uppercase](https://github.com/igraph/igraph.org/tree/master/docs/c/doc). Could also be a bug with Github Pages.

**Comment by szhorvat** [comment]
> Even in the repo, the [filenames are in uppercase](https://github.com/igraph/igraph.org/tree/master/docs/c/doc).

Actually they're not. The only problem ones are `installation`, `introduction` and `tutorial`, which are lowercase in the repo.

**Comment by szhorvat** [comment]
I wonder if this has anything to do with the fact that these are the pre-written xml files. The rest are generated from the xxml ones.

**Comment by ntamas** [comment]
Darn. I think I renamed these to uppercase before the last release for sake of consistency - but Git is probably case-insensitive so it kept the filename as lowercase even though the contents were updated to uppercase. Let me check.

**Comment by szhorvat** [comment]
When I generate the docs locally, these files are generated with uppercase names. But in this repo they're present with lowercase.

So it looks like it's just a problem with what's present in this repo, but not with the doc generation process.

**Comment by ntamas** [comment]
Okay, let's see how it goes now.

**Comment by ntamas** [comment]
Seems like it's fixed now.
