### ISSUE TITLE
Broken links in r-igraph docs

### ISSUE THREAD

**Issue by agila5** [igraph/igraph.org#47]
Dear all, I think there is a problem with the links in r-igraph docs. More precisely, when I check the [online version of the R manual](https://igraph.org/r/doc/), then everything works fine. On the other hand, the links included on any specific page (i.e. the [igraph package page](https://igraph.org/r/doc/aaa-igraph-package.html)) or "See also" section(s) (e.g. [add.edge function](https://igraph.org/r/doc/add_edges.html)) point to an empty page with a 404 -file not found error message (e.g. [here](https://igraph.org/igraph/help/make_ring.html)). 

I'm not sure, but I think that the URL(s) were defined using the wrong pattern (i.e. `igraph/help/something.html` instead of `r/doc/something.html`).

**Comment by ntamas** [comment]
Thanks for the notification, it looks like the URL rewrite part of our build system is broken when we convert the R-generated documentation into the HTML pages on the homepage. I'll fix this.

**Comment by ntamas** [comment]
The links should be fixed now; also, I have fixed links to other packages; these were formerly served from inside-r.org, but now I've migrated them to rdrr.io as the former is not available any more.

**Comment by agila5** [comment]
Thanks!
