### ISSUE TITLE
Version switcher in header should be loaded with JS

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph.org#50]
Right now the version switcher in the header of _all_ documentation pages is embedded in the HTML file. This means that whenever a new Python version is added, Jekyll needs to update the documentation pages of _all_ previous Python versions in order to update the version switcher in the header.

Maybe we should generate the version switcher in the header using some JS code instead? This way we would have a JS file that all HTML pages needing a version switcher would include, and we would only need to update the JS file whenever a new version is added.

**Comment by Yaminyam** [comment]
I saw the history of updating a lot of files while updating this 0.9.8 version.

In my opinion, it looks better to create and manage it in js as you said.
