### ISSUE TITLE
Broken link in tutorial/0.9.8

### ISSUE THREAD

**Issue by h5jam** [igraph/igraph.org#51]
Thank you for your great works! 

I found a broken link while learning from tutorial.

description section of **layout_drl** has a broken link (https://www.cs.sandia.gov/~smartin/software.html).

tutorial page : https://igraph.org/python/tutorial/0.9.8/tutorial.html#layout-algorithms

**Comment by ntamas** [comment]
Thanks for the heads up. Unfortunately all information about the original DrL layout seems to be gone from the Internet; the best link that I could found is [this one](https://www.osti.gov/doecode/biblio/54626) but it's only useful for citations; it provides no information about the method itself.

Would it be okay for you if I simply replaced the original link with this one?

**Comment by h5jam** [comment]
Of course! I think new one is better for anyone who try to approach DrL even no information.

Thanks for fast feedback :)
