### ISSUE TITLE
404 https://igraph.org/c/versions/latest/

### ISSUE THREAD

**Issue by BaseMax** [igraph/igraph.org#55]
https://igraph.org/c/doc/igraph-Separators.html

latest item linked to a broken and 404 page!

**Comment by ntamas** [comment]
Thanks for the heads up, a fix will be deployed in a few minutes.

**Comment by ntamas** [comment]
fixed in https://github.com/igraph/igraph.org/commit/d8eb841fee650f8ebb1f1217377c44c6e84220e8
