### ISSUE TITLE
Create Twitter handle

### ISSUE THREAD

**Issue by buddha314** [igraph/igraph.org#7]
I'm doing a talk where I mention IGraph.  My VP of marketing is very good at getting the word out on social media. Please create a Twitter or FB page for us to reference!

**Comment by gaborcsardi** [comment]
Thanks! Well, having a twitter handle is one thing, but it is only worth it if it is active. We don't have the time for that, and we are also not very good at marketing on social media. :) 

You can mention the twitter or github handles of the two main developers if you like: @gaborcsardi and @ntamas.
